name: issue-open

on: 
  pull_request: 
    types: [closed]

jobs:
  bonjour: 
    runs-on: ubuntu-latest
    steps:
      - name: ouveture d'une issue
        run: echo "Une merge request vient d'etre fermé"




